# Generated by Django 3.2.7 on 2022-02-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_result_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='op1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='op2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='op3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='op4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
