# Generated by Django 3.2.7 on 2022-02-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20220206_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='op1',
        ),
        migrations.RemoveField(
            model_name='result',
            name='op2',
        ),
        migrations.RemoveField(
            model_name='result',
            name='op3',
        ),
        migrations.RemoveField(
            model_name='result',
            name='op4',
        ),
    ]
