# Generated by Django 3.2.7 on 2022-02-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20220206_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='after10',
            name='op1',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='after10',
            name='op2',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='after10',
            name='op3',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='after10',
            name='op4',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='after10',
            name='question',
            field=models.CharField(max_length=900, unique=True),
        ),
    ]
