# Generated by Django 3.2.7 on 2022-02-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20220206_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='After10',
        ),
    ]
