# Generated by Django 3.2.7 on 2022-02-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_delete_after10'),
    ]

    operations = [
        migrations.CreateModel(
            name='After10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=900, unique=True)),
                ('question_type', models.CharField(default=' ', max_length=120)),
                ('op1', models.CharField(max_length=900, null=True)),
                ('op2', models.CharField(max_length=900, null=True)),
                ('op3', models.CharField(max_length=900, null=True)),
                ('op4', models.CharField(max_length=900, null=True)),
                ('correct_answer', models.CharField(default=' ', max_length=120)),
            ],
        ),
    ]
